In [2]:
import pandas as pd

In [3]:
df  = pd.read_csv('transactions.csv')
df

,t_date,cust_id,t_amt,services,products_used,city,state,t_details
0,06-26-2015,4007024,40.33,Exercise & Fitness,Cardio Machine Accessories,Clarksville,Tennessee,credit
1,05-26-2015,4006742,198.44,Exercise & Fitness,Weightlifting Gloves,Long Beach,California,credit
2,06-01-2015,4009775,5.58,Exercise & Fitness,Weightlifting Machine Accessories,Anaheim,California,credit
3,06-05-2015,4002199,198.19,Gymnastics,Gymnastics Rings,Milwaukee,Wisconsin,credit
4,12-17-2015,4002613,98.81,Team Sports,Field Hockey,Nashville,Tennessee,credit
...,...,...,...,...,...,...,...,...
49995,09-18-2015,4005664,53.95,Games,Dice Games,Irving,Texas,credit
49996,10-02-2015,4007287,163.81,Games,Poker Chips & Sets,Kansas City,Missouri,credit
49997,05-03-2015,4003954,35.85,Racquet Sports,Squash,New Orleans,Louisiana,cash
49998,10-23-2015,4007843,180.41,Gymnastics,Vaulting Horses,Berkeley,California,credit
49999,12-14-2015,4001406,168.49,Team Sports,Team Handball,Rockford,Illinois,credit

## 1.What is the total sales amount across all transactions?

In [4]:
df['t_amt'].sum()

np.float64(5110820.54)

## 2.Which month had the highest total transaction amount?

In [5]:
df["t_date"] = pd.to_datetime(df["t_date"])
df["Month"] = df["t_date"].dt.month
df.groupby("Month")["t_amt"].sum().sort_values(ascending=False).head(1)

Month
3    444664.24
Name: t_amt, dtype: float64

## 3.What is the average transaction amount per customer?

In [6]:
df.groupby('cust_id')['t_amt'].mean()

cust_id
4000000    127.444000
4000001    108.945556
4000002     56.165000
4000003    123.670000
4000004    168.135000
              ...
4009995     65.018571
4009996    104.515000
4009997    121.547500
4009998    110.950000
4009999     85.252500
Name: t_amt, Length: 9926, dtype: float64

## 4.What is the trend of total sales over months?

In [7]:

df.groupby("Month")["t_amt"].sum()

Month
1     438165.76
2     395262.37
3     444664.24
4     420695.24
5     432627.58
6     421074.55
7     439560.80
8     434255.01
9     429321.63
10    424856.28
11    408846.35
12    421490.73
Name: t_amt, dtype: float64

## 5.What is the highest single transaction amount recorded?

In [8]:
df['t_amt'].max()

200.0

## 6.Which service category contributes the most to total revenue?

In [9]:
df.groupby('services')['t_amt'].sum().sort_values(ascending=False).head(1)

services
Outdoor Recreation    846678.64
Name: t_amt, dtype: float64

## 7.Which product generated the highest revenue?

In [10]:
df.groupby('products_used')['t_amt'].sum().sort_values(ascending=False).head(1)

products_used
Yoga & Pilates    47804.94
Name: t_amt, dtype: float64

## 8.How does the average transaction amount vary between services?

In [11]:
df.groupby("services")["t_amt"].mean()

services
Air Sports                103.455104
Combat Sports             101.061761
Dancing                   102.907512
Exercise & Fitness        103.660247
Games                     102.272968
Gymnastics                102.385901
Indoor Games              103.074684
Jumping                   102.155171
Outdoor Play Equipment    101.281196
Outdoor Recreation        100.999480
Puzzles                   100.595997
Racquet Sports            103.647461
Team Sports               102.738998
Water Sports              101.899975
Winter Sports             101.217718
Name: t_amt, dtype: float64

## 9.How many unique customers made purchases?

In [12]:
df['cust_id'].nunique()

9926

## 10.Which customers have spent the most overall?

In [13]:
df.groupby("cust_id")["t_amt"].sum().sort_values(ascending=False).head(1)

cust_id
4009485    1973.3
Name: t_amt, dtype: float64

## 11.What is the average number of transactions per customer?

In [14]:
df.groupby("cust_id").size().mean()

np.float64(5.037275841225066)

## 12.Are there customers who made multiple purchases in different categories?

In [15]:
df.groupby("cust_id")["services"].nunique()

cust_id
4000000    4
4000001    8
4000002    2
4000003    3
4000004    3
          ..
4009995    4
4009996    6
4009997    4
4009998    4
4009999    5
Name: services, Length: 9926, dtype: int64

## 13.What percentage of customers are repeat buyers?

In [16]:
repeat = df.groupby("cust_id").size()
(repeat[repeat > 1].count() / repeat.count()) * 100

np.float64(96.5645778762845)

## 14.Which product category has the highest total sales?

In [17]:
df.groupby('products_used')['t_amt'].sum().sort_values(ascending=False).head(1)

products_used
Yoga & Pilates    47804.94
Name: t_amt, dtype: float64

## 15.Which services are most popular by transaction count?

In [18]:
df["services"].value_counts()

services
Outdoor Recreation        8383
Exercise & Fitness        7394
Team Sports               6010
Water Sports              5219
Games                     3666
Gymnastics                3196
Winter Sports             3181
Outdoor Play Equipment    2910
Indoor Games              2799
Jumping                   2015
Combat Sports             1630
Racquet Sports            1611
Air Sports                 960
Puzzles                    612
Dancing                    414
Name: count, dtype: int64

## 16.For each service, which product type is purchased most frequently?

In [19]:
df.groupby(["services","products_used"]).size().reset_index(name="count") \
  .sort_values(["services","count"], ascending=[True, False]) \
  .drop_duplicates("services")

                   services               products_used  count
2                Air Sports                  Parachutes    400
3             Combat Sports                      Boxing    431
7                   Dancing                 Ballet Bars    414
9        Exercise & Fitness  Cardio Machine Accessories    445
32                    Games                     Mahjong    437
35               Gymnastics               Balance Beams    425
47             Indoor Games                    Foosball    422
54                  Jumping                 Trampolines    421
60   Outdoor Play Equipment                  Swing Sets    464
73       Outdoor Recreation                  Lawn Games    466
83                  Puzzles              Jigsaw Puzzles    397
85           Racquet Sports                   Badminton    413
97              Team Sports                      Hockey    434
105            Water Sports                Bodyboarding    425
118           Winter Sports        Cross-Country Skiing    429

## 17.What is the average transaction amount per product type?

In [20]:
df.groupby("products_used")["t_amt"].mean()

products_used
Abdominal Equipment    105.362798
Air Hockey             103.775478
Air Suits              101.421832
Archery                 97.345564
Badminton              108.441138
                          ...
Wetsuits               102.042775
Whitewater Rafting     102.877744
Windsurfing            104.161453
Wrestling               97.895364
Yoga & Pilates         107.668784
Name: t_amt, Length: 125, dtype: float64

## 18.Are there specific services where customers spend significantly more?

In [21]:
df.groupby("services")["t_amt"].mean().sort_values(ascending=False)

services
Exercise & Fitness        103.660247
Racquet Sports            103.647461
Air Sports                103.455104
Indoor Games              103.074684
Dancing                   102.907512
Team Sports               102.738998
Gymnastics                102.385901
Games                     102.272968
Jumping                   102.155171
Water Sports              101.899975
Outdoor Play Equipment    101.281196
Winter Sports             101.217718
Combat Sports             101.061761
Outdoor Recreation        100.999480
Puzzles                   100.595997
Name: t_amt, dtype: float64

## 19.Which state has the highest total sales?

In [22]:
df.groupby("state")["t_amt"].sum().sort_values(ascending=False).head(1)

state
California    702346.23
Name: t_amt, dtype: float64

## 20.Which city records the highest number of transactions?

In [23]:
df["city"].value_counts().head(1)

city
Pasadena    939
Name: count, dtype: int64

## 21.What is the average spending per transaction in each state?

In [24]:
df.groupby("state")["t_amt"].mean()

state
Alabama                 102.487049
Arizona                 102.172241
California              102.652182
Colorado                101.537415
Connecticut              99.982108
District of Columbia    103.800334
Florida                 103.136567
Georgia                 102.330675
Hawaii                  101.536667
Idaho                    98.969538
Illinois                100.166315
Indiana                 100.712664
Iowa                    103.100727
Kansas                  101.436926
Kentucky                104.130392
Louisiana               103.466335
Maryland                100.506913
Massachusetts           104.541571
Michigan                101.547777
Minnesota               103.465157
Mississippi             101.214926
Missouri                100.969040
Nebraska                101.955690
Nevada                  105.434718
New Jersey              103.438005
New York                100.259452
North Carolina          103.033172
Ohio                    101.350817
Oklahoma                104.995771
Oregon                  102.438143
Pennsylvania            102.776034
South Carolina          103.540065
Tennessee                99.265804
Texas                   101.379891
Utah                    104.507560
Virginia                104.976206
Washington              101.401603
Wisconsin               101.953159
Name: t_amt, dtype: float64

## 22.Are certain services more popular in specific states?

In [25]:
df.groupby(["state","services"]).size()

state      services
Alabama    Air Sports             21
           Combat Sports          44
           Dancing                 8
           Exercise & Fitness    160
           Games                  80
                                ...
Wisconsin  Puzzles                15
           Racquet Sports         34
           Team Sports           152
           Water Sports          126
           Winter Sports          64
Length: 570, dtype: int64

## 23.Which states buy the most Outdoor Recreation products?

In [26]:
df[df["products_used"]=="Outdoor Recreation"].groupby("state").size()

Series([], dtype: int64)

## 24.Compare average spending between California and Texas customers.

In [27]:
df[df["state"].isin(["California","Texas"])].groupby("state")["t_amt"].mean()

state
California    102.652182
Texas         101.379891
Name: t_amt, dtype: float64

## 25.Which quarter of the year saw the highest sales?

In [28]:
df["Quarter"] = df["t_date"].dt.quarter
df.groupby("Quarter")["t_amt"].sum().sort_values(ascending=False).head(1)

Quarter
3    1303137.44
Name: t_amt, dtype: float64

## 26.How does total sales vary month by month?

In [29]:
df.groupby("Month")["t_amt"].sum()

Month
1     438165.76
2     395262.37
3     444664.24
4     420695.24
5     432627.58
6     421074.55
7     439560.80
8     434255.01
9     429321.63
10    424856.28
11    408846.35
12    421490.73
Name: t_amt, dtype: float64

## 27.What is the total number of transactions per month?

In [30]:
df.groupby("Month").size()

Month
1     4268
2     3834
3     4360
4     4175
5     4205
6     4171
7     4252
8     4250
9     4160
10    4181
11    3994
12    4150
dtype: int64

## 28.Is there a particular season when sports equipment sales spike?

In [31]:
df[df["products_used"]=="Sports Equipment"] \
  .groupby(df["t_date"].dt.month).size() \
  .sort_values(ascending=False).head(1)

Series([], dtype: int64)

## 29.How many transactions were done using credit?

In [32]:
df[df["t_details"]=="credit"].shape[0]

43151

## 30.What is the total revenue generated from credit transactions?

In [33]:
df[df["t_details"]=="credit"]["t_amt"].sum()

np.float64(4923134.93)

## 31.Is there a difference in average spending between credit and debit customers?

In [34]:
df.groupby("t_details")["t_amt"].mean()

t_details
cash       27.403360
credit    114.090865
Name: t_amt, dtype: float64

## 32.Which states or cities should the company focus on for marketing high-value products?

In [35]:
df.groupby("state")["t_amt"].sum().sort_values(ascending=False)

state
California              702346.23
Texas                   541267.24
Florida                 274858.95
Ohio                    188613.87
Oregon                  187052.05
Washington              181508.87
Colorado                178299.70
Tennessee               177685.79
Virginia                144447.26
Massachusetts           143744.66
New Jersey              136848.48
Illinois                134022.53
Missouri                132471.38
Arizona                 131291.33
Wisconsin               117144.18
Alabama                 116015.34
New York                 98755.56
Michigan                 98196.70
Nevada                   95418.42
South Carolina           94946.24
Kansas                   92713.35
Minnesota                92497.85
Utah                     92071.16
Nebraska                 91556.21
Connecticut              91083.70
Pennsylvania             90442.91
Kentucky                 90281.05
Georgia                  89437.01
North Carolina           87372.13
District of Columbia     49720.36
Louisiana                48836.11
Mississippi              47874.66
Oklahoma                 47668.08
Iowa                     46807.73
Idaho                    45031.14
Maryland                 44926.59
Indiana                  44615.71
Hawaii                   42950.01
Name: t_amt, dtype: float64

## 33.Should more inventory be stocked for Exercise & Fitness products given their popularity?

In [36]:
df["products_used"].value_counts()

products_used
Lawn Games                    466
Swing Sets                    464
Golf                          452
Cardio Machine Accessories    445
Yoga & Pilates                444
                             ...
Kitesurfing                   357
Disc Golf                     357
Surfing                       354
Mechanical Puzzles            215
Air Suits                     191
Name: count, Length: 125, dtype: int64

## 34.Are there product categories with high sales but low average transaction amounts?

In [37]:
df.groupby("products_used")["t_amt"].agg(["sum","mean"]) \
  .sort_values("sum", ascending=False)

                                 sum        mean
products_used
Yoga & Pilates              47804.94  107.668784
Swing Sets                  47204.14  101.733060
Lawn Games                  46828.44  100.490215
Golf                        46577.68  103.047965
Cardio Machine Accessories  46485.54  104.461888
...                              ...         ...
Tetherball                  35611.93   95.989030
Surfing                     35069.08   99.065198
Disc Golf                   33944.02   95.081289
Mechanical Puzzles          20381.67   94.798465
Air Suits                   19371.57  101.421832

[125 rows x 2 columns]

## 35.Are there underperforming service categories that need promotional offers?

In [38]:
df.groupby("services")["t_amt"].sum().sort_values().head(1)

services
Dancing    42603.71
Name: t_amt, dtype: float64